// admin
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_VERIFY = 'AUTH_VERIFY'
export const ACTION_FAIL = 'ACTION_FAIL'

// portfolio

export const GET_EXP_SUCCESS = 'GET_EXP_SUCCESS'
export const GET_EXP_FAIL = 'GET_EXP_FAIL'

export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL'

export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS'
export const GET_SKILLS_FAIL = 'GET_SKILLS_FAIL'