export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const AUTH_FAIL = 'AUTH_FAIL'

export const AUTH_VERIFY = 'AUTH_VERIFY'

export const ACTION_FAIL = 'ACTION_FAIL'